### ISSUE TITLE
Going to / gives a 500 error

### ISSUE THREAD

**Issue by sorrison** [NeCTAR-RC/crams-api#1]
Useful if / can return a 200 so things like load balancers and health checks work

**Comment by RafiFeroze** [comment]
Code modified to display a basic Welcome to Crams - API web page.
Since this code is generated by the application (i.e., not a static page), it should be sufficient to serve as a health check

**Comment by PyMonkey** [comment]
Can this be closed?

I've checked "/" in the current "crams-api.dev.rc.nectar.org.au" and seems to be returning 200.
